teams:
  - name: "Test Team 1 by Terraform"
    description: "The Test Team 1, managed by Terraform"
    members:
      - username: "IronCore864"
        role: "maintainer"
      - username: "IronCore8642"
        role: "member"
  - name: "Test Team 2 by Terraform"
    description: "The Test Team 2, managed by Terraform"
    members:
      - username: "IronCore864"
        role: "maintainer"
    teams:
      - name: "Test Team 3 by Terraform"
        description: "The Test Team 3, managed by Terraform"
        members:
          - username: "IronCore864"
            role: "maintainer"
        teams:
          - name: "Test Team 4 by Terraform"
            description: "The Test Team 4, managed by Terraform"
